# Site settings
title: Maker_Berlin
email: didi@makerberlin.com
url: https://wwww.makerberlin.de
description: "Der Handwerkerservice fuer den Prezlauer Berg Berlin. Wir realiesieren Ihr Projekt helfen bei Holz/Metall und sonstigen Handwerklichen Arbeiten"
keywords: "Handwerker, Berlin Prenzlauer Berg, Berlin"
skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: Geerd Hoffmann

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
contact: static


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


# Build settings
markdown: kramdown
permalink: pretty
